name: Build & Deploy GH-Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@2
    - name: Build site
      uses: node:lts-alpine
      args: |
        yarn install && \
        yarn build && \
        yarn postbuild
