name: Build & Deploy GH-Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Install deps
      run: yarn install
    - name: Build site
      run: yarn build
    - name: Snap site
      run: yarn postbuild
