name: Build & Deploy GH-Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Install deps
      run: yarn install
    - name: Build site
      run: yarn build
    - name: Build PDF
      run: node ./pdf.js
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: build
        fqdn: thatpanda.com
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
